"""
Lindsey Ferretti
Project Euler: Problem 2 - Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def even_fib_sum(prev, curr, do_not_exceed):
    sum = 0
    while curr < do_not_exceed:
        new = prev + curr
        if curr % 2 == 0:
            sum += curr
        prev = curr
        curr = new
    return sum


def main():
    print("Result: " + str(even_fib_sum(1, 2, 4000000)))


main()