/**
 * Lindsey Ferretti
 * Project Euler: Problem 2 - Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class euler002 {

    public static int evenFibSum(int prev, int curr, int doNotExceed) {
        int sum;
        int newTerm = prev + curr;
        for (sum = 0; curr < doNotExceed; newTerm = prev + curr) {
            if (curr % 2 == 0) {                                            // if the current value is even, add it to the sum
                sum += curr;
            }
            prev = curr;
            curr = newTerm;
        }
        return sum;
    }

    public static void main(String[] args) {
        System.out.println("Result: " + evenFibSum(1, 2, 4000000));      // prints the sum
    }

}
